### ISSUE TITLE
Version 1 meta

### ISSUE THREAD

**Issue by madjam002** [ParmenionUX/screenie#3]
- [x] Support matrices (multiple versions for each test e.g for each viewport, browser)
- [ ] Rudimentary watch mode (provide ability for user to manually rerun test)
- [ ] Static browser report at the end of test run
- [ ] Working integration tests and CI
